### ISSUE TITLE
使用WIN10 CMD自带的ping命令批量测试可用的IP

### ISSUE THREAD

**Issue by pklpkl0pkl** [hcfyapp/google-translate-cn-ip#11]
1.把此项目中的全部IP地址保存在本地ips.txt文件中
2.WIN10【文件管理器】打开到ips.txt文件所在目录，点击【文件管理器】路径栏位，输入“cmd”，即代表在ips.txt文件所在目录运行cmd
3.在cmd界面，输入
 for /f "tokens=*" %i in (ips.txt) do ping %i -n 1 -w 1000 
，运行批量ping测试。
其中，各个参数的含义如下：
/f：指定要读取的文件。
"tokens=*"：指定要读取的所有行。
%i：指定变量名。
(ips.txt)：指定要读取的文件名。
ping：指定要执行的命令。
%i：指定变量名。
-n 1：指定ping测试发送的数据包数量为1。
-w 1000：指定ping测试等待响应的时间为1000毫秒。

**Comment by lmk123** [comment]
能 ping 通 IP 并不意味着这个 IP 就能用 :joy:
