### ISSUE TITLE
为什么用cli工具检查的都是不可用的，这几天一直这样，之前就没事

### ISSUE THREAD

**Issue by wangxingzhen** [hcfyapp/google-translate-cn-ip#13]
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/8910c12c-31a3-433c-84eb-ede3b79fe0eb">

**Comment by lmk123** [comment]
因为内置的 IP 都失效了 :joy:

需要我重新在网络上收集一下可用的 IP

**Comment by wangxingzhen** [comment]
原来如此，辛苦辛苦，实测发现216.239.32.40可以用
