### ISSUE TITLE
或者可以选择Microsoft？

### ISSUE THREAD

**Issue by ChanghrSuper** [hcfyapp/google-translate-cn-ip#2]
感觉是不是也可以试试Edge的翻译接口，重定向+修改响应体，有没有插件可以做到修改浏览器请求的结果，Header Editor这个插件貌似只能修改头和重定向，不能修改返回body的内容。

**Comment by lmk123** [comment]
我没太明白你想表达的意思 😂 

这个项目的主要目的是收集谷歌翻译的可用 IP。微软必应翻译属于另一个主题了
