### ISSUE TITLE
Error: [WinError 10054] 错误

### ISSUE THREAD

**Issue by mfkps** [hcfyapp/google-translate-cn-ip#3]
多次测速后
Error: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
出现些错误，怎么解决？

**Comment by lmk123** [comment]
我猜测你是使用的自动化工具来测速的。

这俩软件不是划词翻译开发的，如遇到问题，请去对应的项目 issues 里反馈。

**Comment by mfkps** [comment]
![image](https://user-images.githubusercontent.com/10321631/210160175-f9f178f2-de9a-494f-b7a1-6bfce02d2c69.png)
直接跑 checker.py

**Comment by lmk123** [comment]
这个脚本其实是工具 https://github.com/GoodCoder666/GoogleTranslate_IPFinder 的作者 GoodCoder666 提交的，我本身对 python 不太熟。

我建议你改为使用他开发的软件来测速，这个测速脚本我准备从仓库里删除了。

**Comment by mfkps** [comment]
OK，谢谢
