### ISSUE TITLE
报错了， 打不开。 ggc  无法运行。

### ISSUE THREAD

**Issue by ezraliyzh** [hcfyapp/google-translate-cn-ip#7]
Downloading the file from https://cdn.jsdelivr.net/npm/@hcfy/google-translate-ip/ips.txt
Failed to load host. Error details:
Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by lmk123** [comment]
报这个错说明在下载 https://cdn.jsdelivr.net/npm/@hcfy/google-translate-ip/ips.txt 这个文件的时候失败了，但我试了一下这个地址无论挂不挂梯子都是能正常打开的，你看看你能不能正常打开

**Comment by ezraliyzh** [comment]
居然  有文字了！！！！    我。。。。
我用的是  powershell，  然后，  我的设置  背景  是绿色的。  结果文字 看不到。。。。  哈哈哈哈

**Comment by ezraliyzh** [comment]
需要翻墙，  仍然需要翻墙强才能用。

**Comment by lmk123** [comment]
测了一下还真是……`cdn.jsdelivr.net` 在国内很多地方都打不开（虽然在我这是能打开的

https://tool.chinaz.com/speedtest/cdn.jsdelivr.net/npm/@hcfy/google-translate-ip/ips.txt

那你可以把这个文件下载到你电脑里然后用 `ggc -f ips.txt` 运行

https://github.com/hcfyapp/google-translate-cn-ip/blob/master/packages/google-translate-ip/ips.txt

**Comment by ezraliyzh** [comment]
明白，  感谢， 感谢。  为什么， 我的文字是  绿色的， 居然导致 我看不见 文字。

**Comment by lmk123** [comment]
> 为什么， 我的文字是 绿色的

这我就不清楚了，你看看你是不是设置过什么。ggc 输出文字的时候是没有带任何颜色的
